apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-project
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: chatproject
          image: khun90/chat_project
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 10.10.10.1
  externalIPs:
    - 10.10.10.2
