apiVersion: v1
kind: Service
metadata:
  name: hellocloud-service
  labels:
    app: hellocloud-service
spec:
  type: NodePort
  selector:
    app: hellocloud
  ports:
  - name: container-one
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  - name: container-two
    port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30002
  - name: container-three
    port: 7070
    protocol: TCP
    targetPort: 7070
    nodePort: 30003